# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Calls(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def calls(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Call]: ...

    def __init__(self,
        *,
        calls : typing___Optional[typing___Iterable[type___Call]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"calls",b"calls"]) -> None: ...
type___Calls = Calls

class Call(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: builtin___int = ...
    uuid: typing___Text = ...
    created_at: typing___Text = ...
    caller_number: typing___Text = ...
    virtual_number: typing___Text = ...
    audio_base_path: typing___Text = ...
    audio_identifier: typing___Text = ...
    duration: builtin___float = ...
    flow_version: typing___Text = ...

    @property
    def turns(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Turn]: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        uuid : typing___Optional[typing___Text] = None,
        created_at : typing___Optional[typing___Text] = None,
        caller_number : typing___Optional[typing___Text] = None,
        virtual_number : typing___Optional[typing___Text] = None,
        audio_base_path : typing___Optional[typing___Text] = None,
        audio_identifier : typing___Optional[typing___Text] = None,
        duration : typing___Optional[builtin___float] = None,
        flow_version : typing___Optional[typing___Text] = None,
        turns : typing___Optional[typing___Iterable[type___Turn]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"audio_base_path",b"audio_base_path",u"audio_identifier",b"audio_identifier",u"caller_number",b"caller_number",u"created_at",b"created_at",u"duration",b"duration",u"flow_version",b"flow_version",u"id",b"id",u"turns",b"turns",u"uuid",b"uuid",u"virtual_number",b"virtual_number"]) -> None: ...
type___Call = Call

class Turn(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    TypeValue = typing___NewType('TypeValue', builtin___int)
    type___TypeValue = TypeValue
    Type: _Type
    class _Type(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Turn.TypeValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNKNOWN = typing___cast(Turn.TypeValue, 0)
        ACTION = typing___cast(Turn.TypeValue, 1)
        INPUT = typing___cast(Turn.TypeValue, 2)
        RESPONSE = typing___cast(Turn.TypeValue, 3)
        VALIDATION = typing___cast(Turn.TypeValue, 4)
    UNKNOWN = typing___cast(Turn.TypeValue, 0)
    ACTION = typing___cast(Turn.TypeValue, 1)
    INPUT = typing___cast(Turn.TypeValue, 2)
    RESPONSE = typing___cast(Turn.TypeValue, 3)
    VALIDATION = typing___cast(Turn.TypeValue, 4)
    type___Type = Type

    id: builtin___int = ...
    uuid: typing___Text = ...
    created_at: typing___Text = ...
    type: type___Turn.TypeValue = ...
    sub_type: typing___Text = ...
    text: typing___Text = ...
    audio_base_path: typing___Text = ...
    audio_identifier: typing___Text = ...
    state: typing___Text = ...
    asr_context: typing___Text = ...
    asr_provider: typing___Text = ...
    language: typing___Text = ...

    @property
    def utterances(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Utterance]: ...

    @property
    def prediction(self) -> type___Prediction: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        uuid : typing___Optional[typing___Text] = None,
        created_at : typing___Optional[typing___Text] = None,
        type : typing___Optional[type___Turn.TypeValue] = None,
        sub_type : typing___Optional[typing___Text] = None,
        text : typing___Optional[typing___Text] = None,
        utterances : typing___Optional[typing___Iterable[type___Utterance]] = None,
        audio_base_path : typing___Optional[typing___Text] = None,
        audio_identifier : typing___Optional[typing___Text] = None,
        state : typing___Optional[typing___Text] = None,
        asr_context : typing___Optional[typing___Text] = None,
        asr_provider : typing___Optional[typing___Text] = None,
        language : typing___Optional[typing___Text] = None,
        prediction : typing___Optional[type___Prediction] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"prediction",b"prediction"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"asr_context",b"asr_context",u"asr_provider",b"asr_provider",u"audio_base_path",b"audio_base_path",u"audio_identifier",b"audio_identifier",u"created_at",b"created_at",u"id",b"id",u"language",b"language",u"prediction",b"prediction",u"state",b"state",u"sub_type",b"sub_type",u"text",b"text",u"type",b"type",u"utterances",b"utterances",u"uuid",b"uuid"]) -> None: ...
type___Turn = Turn

class Prediction(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def intents(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Intent]: ...

    def __init__(self,
        *,
        intents : typing___Optional[typing___Iterable[type___Intent]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"intents",b"intents"]) -> None: ...
type___Prediction = Prediction

class Intent(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Slot(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        name: typing___Text = ...
        type: typing___Text = ...

        @property
        def values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___any_pb2___Any]: ...

        def __init__(self,
            *,
            name : typing___Optional[typing___Text] = None,
            type : typing___Optional[typing___Text] = None,
            values : typing___Optional[typing___Iterable[google___protobuf___any_pb2___Any]] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"type",b"type",u"values",b"values"]) -> None: ...
    type___Slot = Slot

    name: typing___Text = ...
    score: builtin___float = ...

    @property
    def slots(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Intent.Slot]: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        score : typing___Optional[builtin___float] = None,
        slots : typing___Optional[typing___Iterable[type___Intent.Slot]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"score",b"score",u"slots",b"slots"]) -> None: ...
type___Intent = Intent

class Utterance(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Alternative(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        transcript: typing___Text = ...
        confidence: builtin___float = ...
        am_score: builtin___float = ...
        lm_score: builtin___float = ...

        def __init__(self,
            *,
            transcript : typing___Optional[typing___Text] = None,
            confidence : typing___Optional[builtin___float] = None,
            am_score : typing___Optional[builtin___float] = None,
            lm_score : typing___Optional[builtin___float] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"am_score",b"am_score",u"confidence",b"confidence",u"lm_score",b"lm_score",u"transcript",b"transcript"]) -> None: ...
    type___Alternative = Alternative


    @property
    def alternatives(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Utterance.Alternative]: ...

    def __init__(self,
        *,
        alternatives : typing___Optional[typing___Iterable[type___Utterance.Alternative]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"alternatives",b"alternatives"]) -> None: ...
type___Utterance = Utterance
